language: python

python:
  - 2.7

sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.9

env:
  matrix:
    - >
      BUILD_SCRIPT="./configure &&
      make -j 2 && make -j 2 check"

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir -p "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - ls -l /usr/bin/gfortran-4.9
  - export FC=/usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gfortran-4.9 "$HOME/.local/bin/gfortran" 
  - gfortran --version

script:
  - echo $BUILD_SCRIPT
  - bash <<<$BUILD_SCRIPT
