PROGRAM main
    use mod_poscar
    use mod_comp
logical::ex_poscar

call poscar()

OPEN (UNIT=11,FILE="STRU")

WRITE(11,'("#STRU Generated by pos2stru.")')
WRITE(11,'("ATOMIC_SPECIES")')

DO I =1,ntype
WRITE(11,"(a2,a,a)")ele_name(I),"  1.00","  ./" 
ENDDO
WRITE(11,'(" ")')

WRITE(11,'("NUMERICAL_ORBITAL")')
WRITE(11,'(" ")')
WRITE(11,'("LATTICE_CONSTANT")')
WRITE(11,"(1F,A)")alatt/AUTOA,"    # Angstrom to Bohr"
WRITE(11,'(" ")')
WRITE(11,'("LATTICE_VECTORS")')
WRITE(11,"(3F)")ACELL(:,1)
WRITE(11,"(3F)")ACELL(:,2)                                                                                                     
WRITE(11,"(3F)")ACELL(:,3)               
WRITE(11,'(" ")')
WRITE(11,'("ATOMIC_POSITIONS")') 


IF (cartesian==.true.) THEN
   WRITE(11,'("Cartesian")')
   WRITE(11,'(" ")')
ELSE
   WRITE(11,'("Direct")')
   WRITE(11,'(" ")')
ENDIF

K=1
DO I=1,ntype
   WRITE(11,"(a2,A)")ele_name(I)," #label"
   WRITE(11,'("0"," #magnetism")')
   WRITE(11,'(i0,A)')nitype(I)," #number of atoms"
   IF (cartesian==.true.) THEN
   DO J=1,nitype(I)
      WRITE(11,"(3F,A)")posca(:,K),"  m  1  1  1" !cartesian
      K=K+1
   ENDDO
   ELSE  
   DO J=1,nitype(I)
      WRITE(11,"(3F,A)")pos(:,K),"  m  1  1  1"   !direct
      K=K+1
   ENDDO
   ENDIF
ENDDO
end

